services:
  patient-service:
    build: ./patient-service
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/patient-service-db
      SPRING_DATASOURCE_USERNAME: nayaashb
      SPRING_DATASOURCE_PASSWORD: Ashu@9348
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_PORT: 9001
    depends_on:
      - db
      - billing-service

  billing-service:
    build: ./billing-service
    ports:
      - "4001:4001"
      - "9001:9001"

# Source db with volume and network
  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: nayaashb
      POSTGRES_PASSWORD: Ashu@9348
      POSTGRES_DB: patient-service-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

