POST http://localhost:4000/patients
Content-Type: application/json

{
  "name":"Ashutosh Nayak",
  "email":"ashutoshnayak410@gmail",
  "address":"123 Perungudi",
  "gender": "Male",
  "dateOfBirth": "1998-04-06",
  "registerDate": "2026-03-27"

}